package mocks

import "github.com/stretchr/testify/mock"

// automatically generated by mockery

// error is an autogenerated mock type for the error type
type error struct {
	mock.Mock
}

// Error provides a mock function with given fields:
func (_m *error) Error() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
